% Author: Carlos Mecha
\ProvidesClass{template/resume}[2016/01/06 Default résumé template.]

\NeedsTeXFormat{LaTeX2e}
\LoadClass[a4paper,9pt]{extarticle}

% Packages
\usepackage[spanish,activeacute]{babel}
\usepackage{hyperref}

% Format
\usepackage[top=2.2cm, bottom=2.2cm, left=2cm, right=2cm]{geometry}
\usepackage[scaled]{helvet}
\renewcommand*\familydefault{\sfdefault}
\thispagestyle{empty}
\setlength{\parindent}{0in}

% Other options

