% Author: Carlos Mecha
\ProvidesClass{template/resume}[2013/03/11 Default résumé template.]

\NeedsTeXFormat{LaTeX2e}
\LoadClass[a4paper,9pt]{extarticle}

% Packages
\usepackage[spanish,activeacute]{babel}
\usepackage{hyperref}

% Format
\usepackage[top=1cm, bottom=1cm, left=1.7cm, right=1.7cm]{geometry}
\usepackage[scaled]{helvet}
\renewcommand*\familydefault{\sfdefault}
\thispagestyle{empty}
\setlength{\parindent}{0in}

% Other options

